# ─────────────────────────────────────────────────────────────────────────────
#  CODE GENERATOR  –  walks the AST and emits Python source code
# ─────────────────────────────────────────────────────────────────────────────
import re
from parser import (ProgramNode, DeclNode, AssignNode, PrintNode, ForNode,
                    IntLit, RealLit, StrLit, IdentRef)

# Maps our type keywords to Python type names (used in comments)
TYPE_MAP = {'INTEGER': 'int', 'REAL': 'float', 'STRING': 'str'}

# Regex that finds [VarName] interpolation markers inside strings
INTERP_RE = re.compile(r'\[(\w+)\]')


class CodeGenError(Exception):
    pass


class CodeGenerator:
    """
    Walks the AST and produces a Python script as a string.
    Indentation is managed with a simple depth counter.
    """

    def __init__(self):
        self._lines  = []
        self._indent = 0
        self._vars   = {}   # name → declared type

    # ── helpers ───────────────────────────────────────────────────────────

    def _emit(self, line=''):
        self._lines.append('    ' * self._indent + line)

    def _indent_in(self):
        self._indent += 1

    def _indent_out(self):
        self._indent -= 1

    def generate(self, node: ProgramNode) -> str:
        self._emit('# ── Generated by MiniLang Compiler ──')
        self._emit()
        self._gen_program(node)
        return '\n'.join(self._lines)

    # ── program ───────────────────────────────────────────────────────────

    def _gen_program(self, node: ProgramNode):
        for stmt in node.body:
            self._gen_stmt(stmt)

    # ── dispatch ──────────────────────────────────────────────────────────

    def _gen_stmt(self, node):
        if   isinstance(node, DeclNode):   self._gen_decl(node)
        elif isinstance(node, AssignNode): self._gen_assign(node)
        elif isinstance(node, PrintNode):  self._gen_print(node)
        elif isinstance(node, ForNode):    self._gen_for(node)
        else:
            raise CodeGenError(f"Unknown AST node: {type(node)}")

    # ── declaration  →  typed comment + default initialisation ───────────

    def _gen_decl(self, node: DeclNode):
        py_type = TYPE_MAP[node.dtype]
        default = {'int': '0', 'float': '0.0', 'str': '""'}[py_type]
        for name in node.names:
            self._vars[name] = node.dtype
            self._emit(f'{name}: {py_type} = {default}  # declared as {node.dtype}')

    # ── assignment ────────────────────────────────────────────────────────

    def _gen_assign(self, node: AssignNode):
        rhs = self._gen_expr(node.value)
        self._emit(f'{node.name} = {rhs}')

    # ── print  (handles [var] string interpolation) ───────────────────────

    def _gen_print(self, node: PrintNode):
        raw = node.value.value          # the raw string content

        if INTERP_RE.search(raw):
            # Convert [VarName] → {VarName} and emit an f-string
            py_str = INTERP_RE.sub(r'{\1}', raw)
            # Escape any existing braces that are NOT our substitutions
            # (already done by the substitution above; just wrap in f"")
            self._emit(f'print(f"{py_str}")')
        else:
            self._emit(f'print("{raw}")')

    # ── for loop ──────────────────────────────────────────────────────────

    def _gen_for(self, node: ForNode):
        start = self._gen_expr(node.start)
        stop  = self._gen_expr(node.stop)
        # range(start, stop+1) to make the loop inclusive (FOR I:=1 TO 5 → 1..5)
        self._emit(f'for {node.var} in range({start}, {stop} + 1):')
        self._indent_in()
        for stmt in node.body:
            self._gen_stmt(stmt)
        self._indent_out()

    # ── expression ────────────────────────────────────────────────────────

    def _gen_expr(self, node) -> str:
        if   isinstance(node, IntLit):   return str(node.value)
        elif isinstance(node, RealLit):  return repr(node.value)
        elif isinstance(node, StrLit):   return f'"{node.value}"'
        elif isinstance(node, IdentRef): return node.name
        else:
            raise CodeGenError(f"Unknown expression node: {type(node)}")
